t(2,poland,ngoorgs3,ussr).
t(2,india,intergovorgs,israel).
t(2,israel,commonbloc1,cuba).
t(2,usa,independence,china).
t(2,burma,reldiplomacy,ussr).
t(2,uk,pprotests,ussr).
t(2,indonesia,militaryactions,uk).
t(2,poland,weightedunvote,netherlands).
t(2,china,intergovorgs3,india).
t(2,burma,relintergovorgs,usa).
t(2,israel,ngoorgs3,brazil).
t(2,india,intergovorgs,egypt).
t(2,netherlands,ngo,india).
t(2,ussr,booktranslations,usa).
t(2,usa,militaryalliance,netherlands).
t(2,india,commonbloc1,poland).
t(2,cuba,reldiplomacy,egypt).
t(2,usa,weightedunvote,israel).
t(2,cuba,ngoorgs3,israel).
t(2,china,embassy,burma).
t(2,netherlands,embassy,india).
t(2,egypt,embassy,uk).
t(2,india,relexports,ussr).
t(2,indonesia,accusation,uk).
t(2,egypt,officialvisits,ussr).
t(2,brazil,intergovorgs,cuba).
t(2,china,relexports,cuba).
t(2,ussr,relintergovorgs,brazil).
t(2,usa,ngoorgs3,netherlands).
t(2,jordan,reltreaties,indonesia).
t(2,indonesia,violentactions,uk).
t(2,poland,reldiplomacy,usa).
t(2,usa,unweightedunvote,israel).
t(2,china,relintergovorgs,brazil).
t(2,burma,reltreaties,china).
t(2,ussr,blockpositionindex,uk).
t(2,cuba,reldiplomacy,china).
t(2,egypt,ngoorgs3,usa).
t(2,cuba,relexports,ussr).
t(2,burma,relintergovorgs,israel).
t(2,ussr,relbooktranslations,usa).
t(2,china,intergovorgs3,ussr).
t(2,india,reltreaties,usa).
t(2,ussr,blockpositionindex,burma).
t(2,poland,weightedunvote,uk).
t(2,ussr,independence,china).
t(2,ussr,relngo,poland).
t(2,india,relintergovorgs,brazil).
t(2,china,negativecomm,india).
t(2,usa,officialvisits,indonesia).
t(2,cuba,independence,usa).
t(2,uk,tourism3,egypt).
t(2,cuba,negativebehavior,uk).
t(2,poland,reltreaties,ussr).
t(2,israel,booktranslations,ussr).
t(2,burma,reldiplomacy,egypt).
t(2,china,officialvisits,indonesia).
t(2,usa,weightedunvote,cuba).
t(2,uk,weightedunvote,cuba).
t(2,china,embassy,egypt).
t(2,israel,intergovorgs3,egypt).
t(2,uk,timesinceally,usa).
t(2,cuba,intergovorgs3,uk).
t(2,jordan,reldiplomacy,usa).
t(2,india,relexports,uk).
t(2,indonesia,reldiplomacy,egypt).
t(2,egypt,embassy,cuba).
t(2,israel,timesincewar,jordan).
t(2,uk,relngo,usa).
t(2,poland,ngo,india).
t(2,indonesia,relngo,cuba).
t(2,burma,dependent,uk).
t(2,netherlands,treaties,usa).
t(2,usa,militaryalliance,uk).
t(2,jordan,relintergovorgs,poland).
t(2,uk,intergovorgs3,brazil).
t(2,poland,reldiplomacy,cuba).
t(2,usa,embassy,uk).
t(2,uk,ngo,poland).
t(2,ussr,reldiplomacy,usa).
t(2,egypt,reltreaties,poland).
t(2,indonesia,embassy,burma).
t(2,poland,commonbloc2,ussr).
t(2,indonesia,expeldiplomats,cuba).
t(2,israel,relngo,usa).
t(2,israel,relngo,india).
t(2,jordan,relngo,brazil).
t(2,usa,negativebehavior,egypt).
t(2,indonesia,ngoorgs3,netherlands).
t(2,usa,accusation,cuba).
t(2,indonesia,militaryalliance,usa).
t(2,china,commonbloc0,brazil).
t(2,usa,reltourism,egypt).
t(2,china,embassy,indonesia).
t(2,egypt,reldiplomacy,usa).
t(2,china,intergovorgs3,usa).
t(2,india,timesinceally,cuba).
t(2,cuba,reltreaties,uk).
t(2,burma,intergovorgs3,indonesia).
t(2,india,nonviolentbehavior,china).
t(2,ussr,timesinceally,china).
t(2,jordan,intergovorgs3,israel).
t(2,cuba,relintergovorgs,egypt).
t(2,indonesia,students,usa).
t(2,indonesia,ngoorgs3,india).
t(2,uk,timesinceally,cuba).
t(2,burma,treaties,china).
t(2,netherlands,tourism3,uk).
t(2,israel,intergovorgs3,brazil).
t(2,uk,timesinceally,ussr).
t(2,india,commonbloc1,china).
t(2,cuba,timesincewar,usa).
t(2,jordan,relintergovorgs,cuba).
t(2,indonesia,negativecomm,china).
t(2,uk,unweightedunvote,jordan).
t(2,uk,conferences,indonesia).
t(2,netherlands,commonbloc1,burma).
t(2,indonesia,negativecomm,uk).
t(2,indonesia,commonbloc2,burma).
t(2,egypt,treaties,china).
t(2,netherlands,embassy,china).
t(2,indonesia,reltreaties,china).
t(2,netherlands,ngoorgs3,india).
t(2,burma,commonbloc1,brazil).
t(2,egypt,embassy,burma).
t(2,poland,intergovorgs,israel).
t(2,jordan,officialvisits,egypt).
t(2,cuba,reltreaties,china).
t(2,egypt,timesinceally,ussr).
t(2,poland,intergovorgs3,israel).
t(2,jordan,ngoorgs3,usa).
t(2,indonesia,relngo,usa).
t(2,brazil,embassy,uk).
t(2,cuba,officialvisits,china).
t(2,brazil,intergovorgs3,usa).
t(2,usa,negativecomm,brazil).
t(2,netherlands,lostterritory,indonesia).
t(2,usa,weightedunvote,ussr).
t(2,egypt,ngoorgs3,brazil).
t(2,netherlands,relintergovorgs,uk).
t(2,egypt,ngoorgs3,netherlands).
t(2,egypt,commonbloc1,uk).
t(2,jordan,commonbloc2,indonesia).
t(2,ussr,embassy,netherlands).
t(2,netherlands,embassy,ussr).
t(2,netherlands,tourism3,ussr).
t(2,netherlands,commonbloc0,china).
t(2,uk,timesinceally,egypt).
t(2,egypt,negativebehavior,israel).
t(2,jordan,weightedunvote,uk).
t(2,poland,relintergovorgs,usa).
t(2,netherlands,relexportbooks,uk).
t(2,burma,ngoorgs3,israel).
t(2,india,relexports,usa).
t(2,poland,independence,uk).
t(2,egypt,treaties,indonesia).
t(2,indonesia,embassy,cuba).
t(2,cuba,tourism3,ussr).
t(2,usa,timesinceally,cuba).
t(2,poland,reldiplomacy,india).
t(2,usa,timesinceally,netherlands).
t(2,egypt,commonbloc2,india).
t(2,netherlands,intergovorgs,indonesia).
t(2,usa,blockpositionindex,ussr).
t(2,china,relexports,ussr).
t(2,israel,embassy,brazil).
t(2,usa,embassy,brazil).
t(2,burma,relngo,israel).
t(2,china,officialvisits,burma).
t(2,brazil,commonbloc1,india).
t(2,israel,intergovorgs,egypt).
t(2,netherlands,commonbloc2,uk).
t(2,egypt,independence,brazil).
t(2,burma,relintergovorgs,egypt).
t(2,usa,conferences,indonesia).
t(2,brazil,exports3,usa).
t(2,egypt,commonbloc1,brazil).
t(2,burma,blockpositionindex,usa).
t(2,egypt,embassy,ussr).
t(2,china,timesinceally,brazil).
t(2,china,accusation,uk).
t(2,uk,embassy,netherlands).
t(2,india,intergovorgs,burma).
t(2,usa,reltourism,india).
t(2,indonesia,commonbloc1,netherlands).
t(2,poland,relexports,usa).
t(2,ussr,timesinceally,brazil).
t(2,usa,ngoorgs3,uk).
t(2,brazil,intergovorgs,poland).
t(2,india,students,usa).
t(2,egypt,independence,usa).
t(2,india,timesinceally,brazil).
t(2,uk,duration,indonesia).
t(2,indonesia,reldiplomacy,uk).
t(2,uk,intergovorgs3,netherlands).
t(2,israel,intergovorgs3,usa).
t(2,burma,exports3,india).
t(2,burma,reldiplomacy,indonesia).
t(2,jordan,relngo,usa).
t(2,israel,commonbloc1,netherlands).
t(2,jordan,ngoorgs3,netherlands).
