t(netherlands,militaryalliance,uk).
t(egypt,intergovorgs3,usa).
t(jordan,relbooktranslations,usa).
t(poland,timesincewar,ussr).
t(uk,negativebehavior,ussr).
t(poland,relintergovorgs,uk).
t(usa,weightedunvote,india).
t(china,accusation,india).
t(uk,unweightedunvote,egypt).
t(poland,embassy,netherlands).
t(jordan,commonbloc1,ussr).
t(cuba,relintergovorgs,indonesia).
t(jordan,commonbloc2,israel).
t(uk,intergovorgs3,usa).
t(israel,commonbloc1,usa).
t(uk,ngoorgs3,brazil).
t(indonesia,commonbloc1,cuba).
t(usa,embassy,netherlands).
t(netherlands,exports3,uk).
t(usa,economicaid,israel).
t(egypt,booktranslations,usa).
t(brazil,weightedunvote,uk).
t(brazil,relexports,uk).
t(india,relbooktranslations,uk).
t(usa,intergovorgs,netherlands).
t(uk,independence,cuba).
t(egypt,reltreaties,china).
t(china,negativebehavior,uk).
t(usa,ngo,poland).
t(uk,weightedunvote,netherlands).
t(india,ngoorgs3,brazil).
t(netherlands,commonbloc1,indonesia).
t(usa,blockpositionindex,india).
t(israel,embassy,poland).
t(israel,commonbloc2,egypt).
t(egypt,embassy,brazil).
t(poland,embassy,cuba).
t(burma,relintergovorgs,uk).
t(uk,relexports,usa).
t(egypt,relstudents,uk).
t(brazil,intergovorgs,uk).
t(indonesia,commonbloc1,china).
t(indonesia,exports3,china).
t(israel,embassy,netherlands).
t(india,commonbloc1,cuba).
t(cuba,commonbloc2,poland).
t(china,aidenemy,usa).
t(brazil,embassy,poland).
t(jordan,eemigrants,usa).
t(egypt,intergovorgs,usa).
t(uk,officialvisits,poland).
t(indonesia,timesincewar,netherlands).
t(indonesia,unoffialacts,usa).
t(brazil,intergovorgs,india).
t(ussr,releconomicaid,poland).
t(cuba,intergovorgs3,egypt).
t(israel,exports3,usa).
t(netherlands,commonbloc0,cuba).
t(usa,ngo,egypt).
t(india,intergovorgs,indonesia).
t(indonesia,relintergovorgs,netherlands).
t(burma,officialvisits,china).
t(usa,intergovorgs3,brazil).
t(india,accusation,china).
t(poland,expeldiplomats,usa).
t(egypt,relngo,uk).
t(indonesia,students,china).
t(usa,nonviolentbehavior,ussr).
t(poland,reldiplomacy,indonesia).
t(usa,negativebehavior,india).
t(usa,independence,netherlands).
t(netherlands,weightedunvote,india).
t(poland,tourism,ussr).
t(brazil,ngo,netherlands).
t(uk,tourism,israel).
t(netherlands,ngo,usa).
t(uk,ngo,israel).
t(usa,ngo,india).
t(china,releconomicaid,egypt).
t(netherlands,relbooktranslations,uk).
t(india,timesinceally,ussr).
t(poland,embassy,china).
t(egypt,negativebehavior,usa).
t(egypt,embassy,china).
t(ussr,intergovorgs3,usa).
t(china,timesincewar,uk).
t(netherlands,weightedunvote,poland).
t(egypt,weightedunvote,usa).
t(uk,independence,poland).
t(ussr,timesinceally,egypt).
t(india,commonbloc1,netherlands).
t(cuba,ngoorgs3,uk).
t(jordan,intergovorgs3,egypt).
t(jordan,timesincewar,israel).
t(indonesia,reldiplomacy,ussr).
t(egypt,timesinceally,netherlands).
t(brazil,timesinceally,cuba).
t(indonesia,conferences,india).
t(uk,commonbloc1,jordan).
t(usa,intergovorgs3,netherlands).
t(egypt,commonbloc2,indonesia).
t(usa,economicaid,jordan).
t(uk,relexportbooks,egypt).
t(israel,commonbloc1,poland).
t(cuba,independence,poland).
t(israel,weightedunvote,uk).
t(india,relngo,uk).
t(uk,intergovorgs,netherlands).
t(usa,tourism,netherlands).
t(poland,commonbloc0,usa).
t(uk,releconomicaid,india).
t(usa,embassy,indonesia).
t(usa,treaties,egypt).
t(ussr,relbooktranslations,uk).
t(india,commonbloc2,jordan).
t(china,ngoorgs3,uk).
t(israel,relngo,uk).
t(cuba,conferences,usa).
t(uk,relintergovorgs,usa).
t(cuba,embassy,egypt).
t(china,militaryactions,usa).
t(indonesia,booktranslations,usa).
t(poland,ngo,usa).
t(poland,accusation,china).
t(uk,commonbloc2,netherlands).
t(usa,exportbooks,india).
t(egypt,commonbloc2,jordan).
t(india,conferences,poland).
t(china,booktranslations,uk).
t(netherlands,relexports,uk).
t(uk,tourism,ussr).
t(china,relintergovorgs,netherlands).
t(ussr,relintergovorgs,usa).
t(israel,commonbloc1,ussr).
t(ussr,boycottembargo,uk).
t(cuba,commonbloc1,burma).
t(brazil,timesinceally,india).
t(israel,ngo,netherlands).
t(poland,conferences,cuba).
t(egypt,relintergovorgs,israel).
t(uk,unweightedunvote,cuba).
t(indonesia,exports3,usa).
t(uk,releconomicaid,jordan).
t(ussr,accusation,israel).
t(poland,embassy,india).
t(china,relngo,india).
t(israel,intergovorgs3,netherlands).
t(uk,conferences,cuba).
t(cuba,blockpositionindex,usa).
t(egypt,independence,poland).
t(israel,blockpositionindex,usa).
t(cuba,relintergovorgs,brazil).
t(jordan,negativecomm,israel).
t(netherlands,intergovorgs,uk).
t(netherlands,independence,jordan).
t(uk,commonbloc1,burma).
t(ussr,reldiplomacy,uk).
t(usa,timesinceally,egypt).
t(india,timesinceally,netherlands).
t(netherlands,embassy,burma).
t(cuba,militaryalliance,ussr).
t(israel,tourism3,uk).
t(brazil,intergovorgs,egypt).
t(uk,unweightedunvote,brazil).
t(indonesia,commonbloc1,uk).
t(burma,commonbloc1,netherlands).
t(ussr,ngoorgs3,netherlands).
t(usa,independence,egypt).
t(brazil,conferences,cuba).
t(jordan,tourism,egypt).
t(india,ngo,uk).
t(usa,commonbloc1,india).
t(ussr,intergovorgs3,netherlands).
t(usa,embassy,jordan).
t(uk,weightedunvote,jordan).
t(burma,relngo,india).
t(egypt,exports3,poland).
t(ussr,embassy,burma).
t(china,independence,cuba).
t(china,commonbloc0,uk).
t(brazil,timesinceally,uk).
t(usa,relngo,israel).
t(usa,releconomicaid,brazil).
t(china,commonbloc1,jordan).
t(uk,timesinceally,israel).
t(usa,relstudents,uk).
t(poland,relngo,netherlands).
t(usa,reltourism,israel).
t(china,commonbloc2,ussr).
t(usa,timesinceally,uk).
t(jordan,accusation,israel).
t(ussr,conferences,burma).
t(netherlands,treaties,india).
t(jordan,relngo,israel).
t(poland,blockpositionindex,uk).
t(usa,officialvisits,burma).
t(netherlands,timesinceally,poland).
t(cuba,embassy,china).
t(brazil,ngoorgs3,usa).
t(indonesia,negativecomm,usa).
t(jordan,relngo,cuba).
t(burma,reldiplomacy,israel).
t(ussr,reldiplomacy,netherlands).
t(ussr,tourism,poland).
t(ussr,intergovorgs,poland).
t(burma,conferences,usa).
t(jordan,commonbloc1,poland).
t(usa,independence,ussr).
t(jordan,relintergovorgs,india).
t(indonesia,reldiplomacy,poland).
t(uk,reltourism,india).
t(egypt,intergovorgs3,netherlands).
t(uk,independence,usa).
t(poland,eemigrants,usa).
t(uk,ngo,egypt).
t(usa,relintergovorgs,netherlands).
t(ussr,reltourism,india).
t(poland,commonbloc1,burma).
t(china,timesinceally,poland).
t(egypt,negativecomm,usa).
t(poland,weightedunvote,usa).
t(usa,independence,cuba).
t(brazil,intergovorgs,usa).
t(cuba,intergovorgs3,israel).
t(china,negativebehavior,ussr).
t(netherlands,commonbloc0,poland).
t(uk,pprotests,poland).
t(ussr,embassy,uk).
t(poland,ngo,brazil).
t(india,unoffialacts,indonesia).
t(brazil,ngo,cuba).
t(burma,conferences,uk).
t(cuba,ngoorgs3,poland).
t(jordan,reltourism,egypt).
t(uk,timesinceally,india).
t(usa,intergovorgs,uk).
t(uk,commonbloc0,poland).
t(uk,tourism3,israel).
t(usa,embassy,ussr).
t(ussr,relintergovorgs,netherlands).
t(jordan,tourism3,egypt).
t(usa,intergovorgs,india).
t(indonesia,embassy,usa).
t(egypt,unweightedunvote,israel).
t(india,relintergovorgs,uk).
t(netherlands,commonbloc1,israel).
t(burma,embassy,india).
t(india,embassy,cuba).
t(usa,conferences,cuba).
t(usa,exportbooks,uk).
t(india,intergovorgs,brazil).
t(uk,ngoorgs3,israel).
t(ussr,reldiplomacy,china).
t(brazil,emigrants3,usa).
t(ussr,independence,poland).
t(burma,relintergovorgs,brazil).
t(usa,embassy,egypt).
t(cuba,exports3,china).
t(netherlands,intergovorgs3,poland).
t(usa,timesinceally,china).
t(indonesia,reldiplomacy,usa).
t(usa,releconomicaid,india).
t(uk,intergovorgs,usa).
t(poland,commonbloc0,brazil).
t(uk,ngo,india).
t(cuba,reltreaties,usa).
t(jordan,timesinceally,egypt).
t(china,ngoorgs3,netherlands).
t(netherlands,independence,usa).
t(indonesia,relintergovorgs,poland).
t(usa,conferences,brazil).
t(egypt,reltreaties,ussr).
t(india,relstudents,usa).
t(uk,unweightedunvote,india).
t(china,militaryalliance,cuba).
t(china,negativebehavior,india).
t(israel,reltreaties,uk).
t(brazil,intergovorgs,netherlands).
t(burma,intergovorgs3,brazil).
t(jordan,relstudents,egypt).
t(uk,ngo,brazil).
t(ussr,reldiplomacy,egypt).
t(cuba,conferences,uk).
t(indonesia,embassy,china).
t(cuba,relngo,egypt).
t(poland,reltreaties,usa).
t(cuba,relintergovorgs,uk).
t(indonesia,commonbloc1,ussr).
t(ussr,conferences,brazil).
t(ussr,embassy,china).
t(ussr,reldiplomacy,poland).
t(china,commonbloc1,burma).
t(ussr,ngoorgs3,israel).
t(usa,intergovorgs3,cuba).
t(poland,ngoorgs3,india).
t(uk,tourism3,usa).
t(burma,relexports,ussr).
t(poland,commonbloc2,china).
t(indonesia,nonviolentbehavior,cuba).
t(jordan,conferences,egypt).
t(india,commonbloc1,uk).
t(china,commonbloc1,egypt).
t(burma,reldiplomacy,usa).
t(uk,embassy,ussr).
t(china,intergovorgs3,uk).
t(usa,relexportbooks,india).
t(egypt,timesinceally,jordan).
t(poland,intergovorgs3,india).
t(cuba,timesinceally,ussr).
t(india,negativebehavior,china).
t(ussr,ngo,poland).
t(indonesia,negativebehavior,netherlands).
t(usa,exportbooks,brazil).
t(cuba,blockpositionindex,brazil).
t(israel,unweightedunvote,cuba).
t(brazil,conferences,ussr).
t(egypt,intergovorgs3,brazil).
t(india,intergovorgs3,uk).
t(indonesia,relintergovorgs,india).
t(ussr,treaties,poland).
t(ussr,treaties,uk).
t(india,treaties,netherlands).
t(usa,independence,brazil).
t(india,unweightedunvote,poland).
t(israel,intergovorgs,uk).
t(usa,booktranslations,cuba).
t(indonesia,reldiplomacy,burma).
t(egypt,intergovorgs,netherlands).
t(usa,officialvisits,india).
t(burma,commonbloc1,ussr).
t(uk,blockpositionindex,ussr).
t(china,timesinceally,usa).
t(poland,timesinceally,egypt).
t(brazil,relngo,usa).
t(china,duration,usa).
t(netherlands,independence,uk).
t(netherlands,intergovorgs,brazil).
t(uk,exportbooks,brazil).
t(usa,duration,china).
t(india,exports3,ussr).
t(india,conferences,burma).
t(india,timesincewar,china).
t(uk,embassy,jordan).
t(ussr,blockpositionindex,india).
t(china,relbooktranslations,usa).
t(israel,ngo,usa).
t(ussr,ngoorgs3,uk).
t(ussr,commonbloc1,israel).
t(netherlands,students,usa).
t(brazil,conferences,usa).
t(ussr,commonbloc1,jordan).
t(ussr,boycottembargo,usa).
t(ussr,officialvisits,china).
t(brazil,timesinceally,china).
t(uk,economicaid,jordan).
t(uk,exportbooks,usa).
t(ussr,militaryalliance,poland).
t(usa,relngo,uk).
t(uk,embassy,israel).
t(poland,embassy,egypt).
t(netherlands,booktranslations,usa).
t(egypt,ngo,netherlands).
t(cuba,intergovorgs3,netherlands).
t(india,attackembassy,indonesia).
t(uk,intergovorgs,poland).
t(israel,embassy,ussr).
t(cuba,independence,china).
t(netherlands,tourism,uk).
t(jordan,relintergovorgs,netherlands).
t(brazil,exports3,uk).
t(brazil,blockpositionindex,china).
t(jordan,relngo,netherlands).
t(indonesia,commonbloc1,usa).
t(uk,officialvisits,ussr).
t(uk,reltreaties,ussr).
t(uk,weightedunvote,ussr).
t(usa,conferences,poland).
t(egypt,accusation,usa).
t(indonesia,blockpositionindex,usa).
t(cuba,weightedunvote,netherlands).
t(netherlands,weightedunvote,egypt).
t(israel,unweightedunvote,poland).
t(poland,intergovorgs3,ussr).
t(poland,embassy,burma).
t(israel,ngo,uk).
t(usa,emigrants3,uk).
t(indonesia,reldiplomacy,netherlands).
t(indonesia,commonbloc2,jordan).
t(burma,conferences,ussr).
t(ussr,commonbloc2,china).
t(uk,weightedunvote,usa).
t(poland,timesinceally,brazil).
t(jordan,relintergovorgs,indonesia).
t(israel,intergovorgs,netherlands).
t(ussr,commonbloc0,usa).
t(ussr,intergovorgs3,poland).
t(netherlands,weightedunvote,cuba).
t(brazil,relintergovorgs,usa).
t(jordan,relngo,india).
t(israel,negativecomm,jordan).
t(egypt,relngo,usa).
t(china,intergovorgs3,cuba).
t(uk,independence,egypt).
t(ussr,reltreaties,poland).
t(uk,pprotests,cuba).
t(israel,relintergovorgs,uk).
t(brazil,timesinceally,ussr).
t(brazil,intergovorgs3,india).
t(netherlands,relngo,usa).
t(egypt,reldiplomacy,india).
t(brazil,booktranslations,uk).
t(egypt,relexports,usa).
t(cuba,commonbloc0,netherlands).
t(china,pprotests,india).
t(poland,reldiplomacy,jordan).
t(indonesia,intergovorgs,brazil).
t(usa,relintergovorgs,uk).
t(burma,exports3,indonesia).
t(egypt,ngoorgs3,uk).
t(usa,weightedunvote,jordan).
t(india,relintergovorgs,usa).
t(poland,conferences,brazil).
t(china,independence,ussr).
t(burma,blockpositionindex,ussr).
t(poland,independence,egypt).
t(uk,commonbloc1,india).
t(brazil,timesinceally,usa).
t(india,intergovorgs3,israel).
t(jordan,students,usa).
t(cuba,independence,netherlands).
t(indonesia,intergovorgs3,brazil).
t(poland,commonbloc1,jordan).
t(china,ngoorgs3,usa).
t(netherlands,militaryalliance,usa).
t(uk,pprotests,egypt).
t(netherlands,timesinceally,uk).
t(netherlands,treaties,uk).
t(uk,commonbloc1,indonesia).
t(brazil,relbooktranslations,uk).
t(ussr,independence,netherlands).
t(poland,dependent,ussr).
t(cuba,ngo,netherlands).
t(india,weightedunvote,netherlands).
t(uk,commonbloc0,ussr).
t(china,accusation,indonesia).
t(egypt,relngo,india).
t(china,reldiplomacy,indonesia).
t(netherlands,intergovorgs3,egypt).
t(india,relintergovorgs,netherlands).
t(uk,reltourism,usa).
t(china,pprotests,ussr).
t(china,commonbloc1,israel).
t(egypt,weightedunvote,netherlands).
t(indonesia,intergovorgs3,egypt).
t(indonesia,violentactions,china).
t(burma,relngo,indonesia).
t(poland,accusation,usa).
t(israel,weightedunvote,netherlands).
t(poland,emigrants3,usa).
t(cuba,intergovorgs3,india).
t(usa,embassy,burma).
t(uk,intergovorgs3,poland).
t(ussr,aidenemy,usa).
t(ussr,blockpositionindex,usa).
t(uk,commonbloc0,cuba).
t(ussr,ngoorgs3,egypt).
t(uk,ngoorgs3,netherlands).
t(usa,blockpositionindex,egypt).
t(cuba,exports3,ussr).
t(india,negativecomm,usa).
t(jordan,embassy,india).
t(netherlands,ngoorgs3,brazil).
t(uk,unweightedunvote,israel).
t(indonesia,conferences,usa).
t(ussr,negativebehavior,usa).
t(usa,tourism,ussr).
t(indonesia,accusation,usa).
t(poland,independence,brazil).
t(uk,conferences,netherlands).
t(brazil,reltreaties,israel).
t(ussr,reltreaties,netherlands).
t(egypt,dependent,uk).
t(netherlands,reltreaties,usa).
t(jordan,treaties,uk).
t(ussr,embassy,usa).
t(israel,relintergovorgs,usa).
t(ussr,ngoorgs3,brazil).
t(uk,unweightedunvote,netherlands).
t(china,booktranslations,usa).
t(poland,treaties,ussr).
t(india,exports3,uk).
t(ussr,reltreaties,china).
t(netherlands,intergovorgs,india).
t(indonesia,relngo,netherlands).
t(uk,ngoorgs3,usa).
t(ussr,weightedunvote,israel).
t(egypt,reltreaties,brazil).
t(brazil,commonbloc0,poland).
t(jordan,ngoorgs3,egypt).
t(cuba,relngo,brazil).
t(india,ngo,usa).
t(cuba,embassy,poland).
t(usa,unweightedunvote,uk).
t(china,reldiplomacy,cuba).
t(egypt,timesinceally,china).
t(israel,relexports,uk).
t(ussr,relexports,cuba).
t(egypt,relbooktranslations,uk).
t(poland,intergovorgs,india).
t(egypt,ngo,uk).
t(brazil,relintergovorgs,netherlands).
t(israel,embassy,burma).
t(ussr,commonbloc2,poland).
t(brazil,embassy,egypt).
t(brazil,reldiplomacy,uk).
t(brazil,independence,usa).
t(egypt,relexports,india).
t(burma,reldiplomacy,uk).
t(uk,ngo,netherlands).
t(jordan,ngoorgs3,brazil).
t(uk,timesinceally,brazil).
t(poland,embassy,indonesia).
t(egypt,ngo,usa).
t(egypt,conferences,jordan).
t(jordan,duration,israel).
t(poland,ngo,israel).
t(ussr,weightedunvote,uk).
t(ussr,pprotests,usa).
t(poland,relngo,uk).
t(ussr,relintergovorgs,poland).
t(uk,eemigrants,usa).
t(poland,reldiplomacy,egypt).
t(poland,relexports,uk).
t(brazil,reldiplomacy,indonesia).
t(india,dependent,uk).
t(uk,blockpositionindex,china).
t(cuba,independence,ussr).
t(israel,exports3,netherlands).
t(ussr,embassy,cuba).
t(china,independence,usa).
t(india,accusation,uk).
t(china,reldiplomacy,uk).
t(cuba,ngoorgs3,india).
t(uk,emigrants3,usa).
t(ussr,intergovorgs3,uk).
t(usa,negativebehavior,cuba).
t(indonesia,ngoorgs3,usa).
t(india,negativebehavior,usa).
t(indonesia,officialvisits,ussr).
t(india,embassy,jordan).
t(uk,embassy,brazil).
t(poland,weightedunvote,israel).
t(burma,weightedunvote,netherlands).
t(indonesia,conferences,burma).
t(cuba,weightedunvote,usa).
t(israel,reltreaties,usa).
t(indonesia,duration,uk).
t(poland,booktranslations,ussr).
t(cuba,accusation,usa).
t(netherlands,unweightedunvote,uk).
t(burma,commonbloc1,china).
t(poland,ngoorgs3,usa).
t(israel,unweightedunvote,india).
t(brazil,embassy,india).
t(israel,relbooktranslations,usa).
t(burma,relexports,china).
t(china,treaties,egypt).
t(egypt,militaryalliance,jordan).
t(brazil,conferences,india).
t(uk,tourism,netherlands).
t(burma,commonbloc2,india).
t(israel,treaties,usa).
t(jordan,exports3,india).
t(egypt,timesincewar,israel).
t(burma,relintergovorgs,india).
t(china,officialvisits,cuba).
t(burma,exports3,china).
t(netherlands,intergovorgs3,india).
t(india,relngo,brazil).
t(uk,commonbloc1,egypt).
t(india,intergovorgs,uk).
t(israel,pprotests,jordan).
t(brazil,blockpositionindex,cuba).
t(netherlands,commonbloc1,egypt).
t(china,violentactions,india).
t(egypt,blockpositionindex,ussr).
t(egypt,exports3,china).
t(cuba,reltreaties,indonesia).
t(brazil,ngoorgs3,uk).
t(indonesia,reldiplomacy,jordan).
t(poland,reldiplomacy,burma).
t(india,commonbloc1,brazil).
t(ussr,officialvisits,uk).
t(indonesia,relbooktranslations,netherlands).
t(burma,booktranslations,uk).
t(indonesia,conferences,uk).
t(cuba,relemigrants,usa).
t(cuba,relngo,uk).
t(usa,reltourism,netherlands).
t(brazil,timesinceally,netherlands).
t(indonesia,ngoorgs3,egypt).
t(ussr,intergovorgs,netherlands).
t(india,ngo,poland).
t(brazil,relstudents,usa).
t(burma,relngo,usa).
t(india,violentactions,china).
t(burma,timesincewar,usa).
t(cuba,reldiplomacy,israel).
t(israel,embassy,uk).
t(burma,intergovorgs3,egypt).
t(ussr,accusation,china).
t(israel,duration,jordan).
t(china,tourism,ussr).
t(burma,relintergovorgs,jordan).
t(jordan,relstudents,usa).
t(egypt,timesinceally,poland).
t(uk,relexportbooks,burma).
t(uk,treaties,usa).
t(cuba,timesinceally,usa).
t(ussr,ngoorgs3,india).
t(netherlands,officialvisits,usa).
t(burma,relintergovorgs,poland).
t(uk,relexports,netherlands).
t(netherlands,commonbloc1,jordan).
t(israel,weightedunvote,poland).
t(india,intergovorgs3,usa).
t(ussr,blockpositionindex,egypt).
t(indonesia,negativebehavior,cuba).
t(india,timesinceally,china).
t(poland,booktranslations,usa).
t(usa,relngo,netherlands).
t(india,embassy,brazil).
t(netherlands,booktranslations,ussr).
t(poland,negativebehavior,usa).
t(india,ngoorgs3,uk).
t(cuba,relngo,india).
t(jordan,weightedunvote,usa).
t(egypt,intergovorgs,indonesia).
t(usa,blockpositionindex,cuba).
t(netherlands,relbooktranslations,usa).
t(indonesia,intergovorgs,usa).
t(israel,tourism,uk).
t(uk,weightedunvote,poland).
t(egypt,ngoorgs3,india).
t(uk,students,usa).
t(uk,tourism,usa).
t(poland,relintergovorgs,israel).
t(egypt,ngoorgs3,israel).
t(ussr,reldiplomacy,india).
t(uk,reltreaties,usa).
t(brazil,reldiplomacy,ussr).
t(uk,booktranslations,ussr).
t(indonesia,reldiplomacy,cuba).
t(china,relngo,netherlands).
t(china,independence,netherlands).
t(usa,releconomicaid,jordan).
t(usa,economicaid,brazil).
t(uk,treaties,india).
t(usa,intergovorgs3,india).
t(jordan,commonbloc1,netherlands).
t(uk,relintergovorgs,netherlands).
t(usa,commonbloc1,indonesia).
t(uk,timesincewar,egypt).
t(egypt,exports3,ussr).
t(brazil,ngoorgs3,india).
t(netherlands,embassy,israel).
t(brazil,relintergovorgs,israel).
t(uk,intergovorgs,cuba).
t(brazil,reldiplomacy,usa).
t(egypt,relngo,brazil).
t(usa,negativebehavior,china).
t(israel,relintergovorgs,india).
t(brazil,commonbloc0,cuba).
t(brazil,ngo,india).
t(indonesia,relngo,poland).
t(cuba,intergovorgs,netherlands).
t(poland,unweightedunvote,india).
t(burma,commonbloc1,uk).
t(poland,commonbloc1,egypt).
t(india,relintergovorgs,israel).
t(usa,militaryalliance,brazil).
t(jordan,reldiplomacy,egypt).
t(china,pprotests,indonesia).
t(usa,ngoorgs3,poland).
t(netherlands,intergovorgs3,usa).
t(china,ngoorgs3,poland).
t(netherlands,blockpositionindex,china).
t(india,eemigrants,usa).
t(cuba,officialvisits,ussr).
t(india,commonbloc2,israel).
t(burma,relngo,cuba).
t(israel,timesinceally,usa).
t(uk,ngo,ussr).
t(poland,booktranslations,uk).
t(israel,ngoorgs3,uk).
t(uk,intergovorgs,indonesia).
t(indonesia,dependent,netherlands).
t(cuba,negativebehavior,usa).
t(india,ngo,brazil).
t(uk,relexportbooks,brazil).
t(india,conferences,usa).
t(netherlands,embassy,uk).
t(india,embassy,netherlands).
t(usa,embassy,india).
t(brazil,ngo,uk).
t(egypt,independence,uk).
t(china,relngo,israel).
t(poland,students,usa).
t(uk,exportbooks,egypt).
t(usa,tourism,israel).
t(poland,reltreaties,china).
t(uk,embassy,india).
t(cuba,timesinceally,uk).
t(china,timesinceally,ussr).
t(uk,embassy,egypt).
t(usa,intergovorgs,poland).
t(usa,ngo,uk).
t(cuba,conferences,ussr).
t(cuba,treaties,uk).
t(uk,tourism,jordan).
t(cuba,independence,egypt).
t(netherlands,commonbloc2,brazil).
t(usa,treaties,netherlands).
t(egypt,embassy,usa).
t(usa,relexports,uk).
t(usa,reltourism,jordan).
t(cuba,relintergovorgs,netherlands).
t(israel,militaryactions,jordan).
t(usa,ngoorgs3,israel).
t(usa,tourism,india).
t(ussr,ngoorgs3,poland).
t(uk,timesinceally,china).
t(egypt,embassy,poland).
t(cuba,embassy,netherlands).
t(poland,conferences,ussr).
t(poland,intergovorgs3,netherlands).
t(china,relngo,ussr).
t(usa,commonbloc0,china).
t(poland,blockpositionindex,brazil).
t(uk,weightedunvote,israel).
t(netherlands,relemigrants,usa).
t(china,commonbloc1,india).
t(china,independence,brazil).
t(israel,relngo,brazil).
t(netherlands,ngo,israel).
t(ussr,timesinceally,usa).
t(ussr,treaties,netherlands).
t(uk,tourism,egypt).
t(netherlands,blockpositionindex,poland).
t(ussr,treaties,usa).
t(ussr,accusation,usa).
t(usa,commonbloc1,jordan).
t(indonesia,embassy,poland).
t(india,timesinceally,poland).
t(usa,commonbloc2,netherlands).
t(usa,negativecomm,cuba).
t(poland,reldiplomacy,israel).
t(ussr,timesinceally,india).
t(uk,nonviolentbehavior,usa).
t(india,pprotests,israel).
t(burma,commonbloc2,jordan).
t(netherlands,timesincewar,indonesia).
t(indonesia,officialvisits,poland).
t(uk,commonbloc2,brazil).
t(poland,intergovorgs3,usa).
t(india,relngo,israel).
t(netherlands,unweightedunvote,ussr).
t(burma,commonbloc1,usa).
t(burma,relngo,uk).
t(jordan,relexports,india).
t(china,intergovorgs3,poland).
t(jordan,reldiplomacy,ussr).
t(brazil,negativebehavior,china).
t(india,booktranslations,uk).
t(indonesia,booktranslations,uk).
t(egypt,reldiplomacy,uk).
t(india,intergovorgs3,netherlands).
t(jordan,blockpositionindex,usa).
t(netherlands,independence,ussr).
t(poland,reltreaties,netherlands).
t(brazil,relngo,uk).
t(jordan,relintergovorgs,burma).
t(poland,blockpositionindex,netherlands).
t(ussr,conferences,indonesia).
t(netherlands,conferences,uk).
t(poland,embassy,uk).
t(ussr,conferences,uk).
t(china,independence,uk).
t(india,treaties,uk).
t(ussr,tourism3,poland).
t(israel,intergovorgs,usa).
t(netherlands,tourism3,usa).
t(indonesia,reldiplomacy,brazil).
t(israel,relngo,poland).
t(poland,relintergovorgs,ussr).
t(brazil,intergovorgs3,cuba).
t(cuba,relngo,poland).
t(usa,treaties,ussr).
t(uk,relemigrants,usa).
t(brazil,embassy,ussr).
t(brazil,commonbloc2,netherlands).
t(brazil,relngo,netherlands).
t(brazil,timesinceally,egypt).
t(netherlands,ngo,ussr).
t(poland,exports3,ussr).
t(burma,ngoorgs3,brazil).
t(uk,negativecomm,ussr).
t(netherlands,reltourism,israel).
t(uk,reltourism,ussr).
t(ussr,intergovorgs3,india).
t(burma,weightedunvote,uk).
t(egypt,students,usa).
t(indonesia,relexports,china).
t(india,weightedunvote,uk).
t(jordan,violentactions,israel).
t(ussr,booktranslations,poland).
t(egypt,embassy,netherlands).
t(ussr,reldiplomacy,indonesia).
t(usa,relngo,india).
t(uk,conferences,poland).
t(brazil,commonbloc2,usa).
t(usa,booktranslations,netherlands).
t(indonesia,relintergovorgs,israel).
t(netherlands,relstudents,usa).
t(cuba,conferences,india).
t(israel,unweightedunvote,uk).
t(cuba,reldiplomacy,ussr).
t(indonesia,relexports,usa).
t(brazil,independence,china).
t(usa,blockpositionindex,jordan).
t(brazil,independence,egypt).
t(egypt,treaties,uk).
t(indonesia,boycottembargo,usa).
t(usa,relexportbooks,uk).
t(ussr,releconomicaid,india).
t(indonesia,relintergovorgs,egypt).
t(israel,relintergovorgs,egypt).
t(china,officialvisits,egypt).
t(indonesia,relexports,ussr).
t(ussr,blockpositionindex,jordan).
t(cuba,reltreaties,india).
t(china,treaties,indonesia).
t(brazil,embassy,usa).
t(netherlands,weightedunvote,burma).
t(indonesia,commonbloc2,india).
t(israel,booktranslations,uk).
t(jordan,pprotests,israel).
t(china,relngo,poland).
t(ussr,militaryalliance,cuba).
t(ussr,timesinceally,poland).
t(brazil,reltreaties,uk).
t(brazil,booktranslations,usa).
t(india,ngoorgs3,usa).
t(usa,conferences,netherlands).
t(ussr,independence,brazil).
t(egypt,weightedunvote,israel).
t(china,treaties,poland).
t(usa,blockpositionindex,israel).
t(burma,embassy,poland).
t(brazil,independence,uk).
t(poland,intergovorgs,brazil).
t(poland,reldiplomacy,china).
t(netherlands,intergovorgs3,israel).
t(indonesia,commonbloc1,brazil).
t(netherlands,independence,egypt).
t(china,blockpositionindex,brazil).
t(ussr,economicaid,cuba).
t(jordan,students,egypt).
t(usa,economicaid,india).
t(usa,booktranslations,ussr).
t(indonesia,relexports,netherlands).
t(egypt,ngoorgs3,poland).
t(china,nonviolentbehavior,usa).
t(poland,unweightedunvote,netherlands).
t(indonesia,unoffialacts,china).
t(netherlands,intergovorgs3,uk).
t(burma,conferences,indonesia).
t(brazil,exports3,netherlands).
t(usa,negativebehavior,ussr).
t(poland,commonbloc0,uk).
t(israel,blockpositionindex,ussr).
t(brazil,intergovorgs3,uk).
t(burma,intergovorgs3,india).
t(poland,timesinceally,india).
t(burma,relngo,brazil).
t(usa,commonbloc1,egypt).
t(india,ngoorgs3,poland).
t(usa,tourism3,uk).
t(brazil,reltreaties,ussr).
t(indonesia,embassy,india).
t(netherlands,relngo,uk).
t(cuba,commonbloc1,indonesia).
t(uk,treaties,poland).
t(ussr,commonbloc0,netherlands).
t(egypt,treaties,usa).
t(israel,commonbloc2,indonesia).
t(brazil,ngo,egypt).
t(usa,timesinceally,india).
t(usa,blockpositionindex,china).
t(egypt,commonbloc1,china).
t(uk,intergovorgs,india).
t(brazil,eemigrants,usa).
t(brazil,embassy,netherlands).
t(netherlands,relexportbooks,usa).
t(china,warning,india).
t(usa,negativebehavior,indonesia).
t(ussr,relngo,india).
t(usa,violentactions,china).
t(poland,reldiplomacy,uk).
t(netherlands,exportbooks,usa).
t(usa,conferences,uk).
t(poland,unweightedunvote,uk).
t(uk,relexportbooks,netherlands).
t(egypt,timesinceally,usa).
t(china,negativecomm,uk).
t(usa,students,uk).
t(china,relngo,brazil).
t(netherlands,exports3,usa).
t(netherlands,ngo,egypt).
t(israel,lostterritory,jordan).
t(cuba,relintergovorgs,india).
t(egypt,exports3,india).
t(ussr,relintergovorgs,uk).
t(uk,relexportbooks,usa).
t(poland,conferences,uk).
t(china,commonbloc2,cuba).
t(china,embassy,poland).
t(usa,timesinceally,ussr).
t(usa,officialvisits,ussr).
t(india,commonbloc2,indonesia).
t(cuba,reltreaties,egypt).
t(netherlands,emigrants3,usa).
t(china,accusation,usa).
t(israel,ngo,poland).
t(cuba,timesinceally,netherlands).
t(brazil,militaryalliance,usa).
t(india,unweightedunvote,ussr).
t(uk,militaryactions,indonesia).
t(ussr,relintergovorgs,israel).
t(india,conferences,uk).
t(usa,militaryalliance,israel).
t(ussr,commonbloc2,cuba).
t(brazil,commonbloc0,china).
t(poland,conferences,usa).
t(jordan,militaryactions,israel).
t(egypt,embassy,india).
t(cuba,ngo,brazil).
t(india,intergovorgs3,indonesia).
t(china,relexports,uk).
t(china,reldiplomacy,poland).
t(ussr,unweightedunvote,india).
t(india,blockpositionindex,usa).
t(cuba,intergovorgs3,usa).
t(indonesia,negativebehavior,usa).
t(netherlands,independence,china).
t(india,pprotests,usa).
t(netherlands,weightedunvote,israel).
t(netherlands,embassy,egypt).
t(india,timesinceally,usa).
t(cuba,commonbloc2,china).
t(usa,releconomicaid,egypt).
t(netherlands,timesinceally,china).
t(brazil,unweightedunvote,israel).
t(india,relngo,netherlands).
t(brazil,intergovorgs,indonesia).
t(poland,intergovorgs3,uk).
t(china,releconomicaid,indonesia).
t(india,ngo,israel).
t(china,timesinceally,uk).
t(india,ngoorgs3,netherlands).
t(israel,officialvisits,uk).
t(israel,unweightedunvote,egypt).
t(uk,intergovorgs,brazil).
t(usa,negativecomm,indonesia).
t(indonesia,relintergovorgs,usa).
t(ussr,weightedunvote,usa).
t(china,commonbloc2,poland).
t(netherlands,tourism3,israel).
t(jordan,negativebehavior,israel).
t(uk,weightedunvote,india).
t(ussr,booktranslations,uk).
t(usa,tourism3,netherlands).
t(uk,tourism,india).
t(ussr,conferences,poland).
t(ussr,negativebehavior,uk).
t(egypt,reltreaties,indonesia).
t(burma,officialvisits,india).
t(china,economicaid,indonesia).
t(ussr,relngo,israel).
t(usa,intergovorgs,israel).
t(usa,militaryalliance,india).
t(uk,reltourism,israel).
t(uk,exportbooks,burma).
t(egypt,weightedunvote,uk).
t(uk,militaryalliance,usa).
t(uk,embassy,indonesia).
t(israel,unweightedunvote,ussr).
t(israel,intergovorgs,poland).
t(india,relbooktranslations,usa).
t(india,intergovorgs,poland).
t(usa,militaryactions,china).
t(usa,relexportbooks,brazil).
t(egypt,independence,cuba).
t(china,relintergovorgs,poland).
t(ussr,unoffialacts,usa).
t(burma,relexports,india).
t(cuba,intergovorgs,usa).
t(burma,timesincewar,uk).
t(egypt,relintergovorgs,usa).
t(indonesia,ngoorgs3,brazil).
t(poland,negativecomm,usa).
t(egypt,reldiplomacy,poland).
t(poland,intergovorgs,ussr).
t(cuba,weightedunvote,uk).
t(indonesia,ngoorgs3,uk).
t(jordan,commonbloc1,cuba).
t(poland,timesinceally,cuba).
t(jordan,relintergovorgs,israel).
t(india,commonbloc1,ussr).
t(egypt,reltreaties,cuba).
t(israel,emigrants3,usa).
t(uk,blockpositionindex,poland).
t(egypt,timesinceally,india).
t(china,reldiplomacy,ussr).
t(usa,intergovorgs,cuba).
t(cuba,reldiplomacy,indonesia).
t(brazil,commonbloc1,burma).
t(egypt,reltreaties,india).
t(brazil,relexports,usa).
t(cuba,commonbloc0,usa).
t(india,ngo,egypt).
t(ussr,conferences,cuba).
t(burma,ngoorgs3,netherlands).
t(poland,embassy,usa).
t(india,officialvisits,burma).
t(brazil,ngo,poland).
t(burma,relexports,indonesia).
t(brazil,intergovorgs,israel).
t(poland,commonbloc1,india).
t(india,relstudents,uk).
t(israel,relintergovorgs,poland).
t(netherlands,treaties,poland).
t(poland,militaryalliance,ussr).
t(netherlands,reltourism,uk).
t(egypt,ngo,israel).
t(poland,timesinceally,china).
t(ussr,blockpositionindex,brazil).
t(ussr,reltourism,poland).
t(china,embassy,india).
t(usa,intergovorgs,indonesia).
t(netherlands,ngo,cuba).
t(china,commonbloc0,usa).
t(jordan,relintergovorgs,usa).
t(usa,treaties,israel).
t(indonesia,intergovorgs,netherlands).
t(brazil,tourism,usa).
t(netherlands,ngoorgs3,israel).
t(uk,reltourism,jordan).
t(usa,exportbooks,china).
t(poland,relngo,ussr).
t(china,independence,jordan).
t(china,boycottembargo,ussr).
t(egypt,relexports,ussr).
t(egypt,independence,ussr).
t(china,ngoorgs3,brazil).
t(jordan,reldiplomacy,uk).
t(ussr,nonviolentbehavior,usa).
t(indonesia,intergovorgs3,india).
t(ussr,intergovorgs,uk).
t(egypt,reldiplomacy,cuba).
t(usa,boycottembargo,ussr).
t(usa,ngo,ussr).
t(israel,accusation,jordan).
t(china,relngo,egypt).
t(israel,commonbloc2,burma).
t(uk,relbooktranslations,ussr).
t(egypt,reltreaties,usa).
t(jordan,commonbloc1,china).
t(uk,relexportbooks,china).
t(china,eemigrants,usa).
t(uk,ngoorgs3,poland).
t(egypt,negativebehavior,uk).
t(poland,treaties,netherlands).
t(cuba,emigrants3,usa).
t(usa,tourism,brazil).
t(usa,commonbloc2,brazil).
t(egypt,reltreaties,israel).
t(netherlands,intergovorgs,ussr).
t(israel,ngo,india).
t(israel,timesinceally,uk).
t(indonesia,relbooktranslations,uk).
t(china,accusation,ussr).
t(burma,commonbloc1,cuba).
t(israel,relexports,usa).
t(india,nonviolentbehavior,usa).
t(china,independence,poland).
t(indonesia,nonviolentbehavior,india).
t(poland,intergovorgs,usa).
t(israel,ngo,egypt).
t(uk,relngo,netherlands).
t(ussr,commonbloc1,india).
t(egypt,reldiplomacy,china).
t(israel,relintergovorgs,netherlands).
t(india,timesinceally,uk).
t(jordan,dependent,uk).
t(uk,independence,china).
t(uk,embassy,burma).
t(cuba,relexports,china).
t(india,weightedunvote,usa).
t(israel,students,usa).
t(usa,embassy,poland).
t(jordan,embassy,egypt).
t(india,unweightedunvote,israel).
t(poland,lostterritory,ussr).
t(india,ngoorgs3,israel).
t(burma,reldiplomacy,india).
t(egypt,relbooktranslations,usa).
t(cuba,unweightedunvote,israel).
t(usa,officialvisits,egypt).
t(netherlands,ngo,poland).
t(israel,ngoorgs3,india).
t(india,reltreaties,uk).
t(burma,exports3,uk).
t(netherlands,timesinceally,cuba).
t(cuba,relngo,netherlands).
t(israel,booktranslations,usa).
t(egypt,relintergovorgs,uk).
t(israel,intergovorgs3,india).
t(israel,commonbloc1,china).
t(indonesia,embassy,brazil).
t(uk,commonbloc1,israel).
t(uk,ngo,usa).
t(india,students,uk).
t(indonesia,embassy,ussr).
t(burma,relngo,netherlands).
t(brazil,commonbloc1,egypt).
t(usa,negativebehavior,poland).
t(uk,weightedunvote,egypt).
t(indonesia,blockpositionindex,ussr).
t(usa,exportbooks,netherlands).
t(uk,exports3,netherlands).
t(usa,weightedunvote,poland).
t(india,commonbloc1,usa).
t(usa,ngo,israel).
t(brazil,blockpositionindex,ussr).
t(india,blockpositionindex,ussr).
t(india,militaryalliance,usa).
t(netherlands,treaties,ussr).
t(ussr,blockpositionindex,indonesia).
t(netherlands,weightedunvote,ussr).
t(indonesia,reldiplomacy,china).
t(china,embassy,ussr).
t(brazil,unweightedunvote,uk).
t(china,negativebehavior,indonesia).
t(uk,officialvisits,usa).
t(cuba,unweightedunvote,uk).
t(usa,relexports,india).
t(china,relbooktranslations,uk).
t(jordan,relngo,burma).
t(poland,conferences,india).
t(brazil,commonbloc2,uk).
t(poland,relbooktranslations,usa).
t(burma,ngoorgs3,usa).
t(burma,booktranslations,usa).
t(cuba,conferences,brazil).
t(ussr,independence,usa).
t(ussr,unweightedunvote,israel).
t(usa,negativecomm,ussr).
t(uk,treaties,jordan).
t(brazil,reltreaties,netherlands).
t(uk,exportbooks,india).
t(egypt,timesinceally,cuba).
t(indonesia,relintergovorgs,brazil).
t(jordan,commonbloc1,uk).
t(uk,independence,jordan).
t(poland,relintergovorgs,india).
t(cuba,reldiplomacy,netherlands).
t(poland,commonbloc0,netherlands).
t(israel,unweightedunvote,brazil).
t(poland,intergovorgs3,egypt).
t(poland,relngo,usa).
t(usa,independence,jordan).
t(netherlands,booktranslations,uk).
t(brazil,relngo,india).
t(israel,relemigrants,usa).
t(egypt,relngo,israel).
t(cuba,embassy,israel).
t(ussr,negativecomm,usa).
t(egypt,commonbloc1,netherlands).
t(indonesia,relngo,brazil).
t(poland,ngo,netherlands).
t(netherlands,timesinceally,egypt).
t(netherlands,relexports,usa).
t(usa,releconomicaid,israel).
t(burma,commonbloc1,poland).
t(brazil,nonviolentbehavior,usa).
t(brazil,relbooktranslations,usa).
t(cuba,treaties,usa).
t(usa,treaties,cuba).
t(netherlands,conferences,usa).
t(ussr,intergovorgs,usa).
t(cuba,commonbloc1,israel).
t(cuba,relintergovorgs,usa).
t(usa,commonbloc2,uk).
t(egypt,independence,jordan).
t(indonesia,nonviolentbehavior,china).
t(usa,accusation,ussr).
t(netherlands,exportbooks,uk).
t(egypt,intergovorgs3,india).
t(uk,treaties,ussr).
t(usa,blockpositionindex,indonesia).
t(israel,tourism3,usa).
t(poland,independence,cuba).
t(indonesia,reldiplomacy,india).
t(egypt,students,uk).
t(poland,pprotests,usa).
t(indonesia,relintergovorgs,burma).
t(brazil,independence,cuba).
t(jordan,ngoorgs3,israel).
t(cuba,exports3,uk).
t(jordan,commonbloc1,brazil).
t(jordan,weightedunvote,netherlands).
t(poland,commonbloc2,cuba).
t(indonesia,embassy,netherlands).
t(china,blockpositionindex,usa).
t(egypt,intergovorgs,uk).
t(indonesia,commonbloc2,israel).
t(uk,embassy,china).
t(china,reldiplomacy,netherlands).
t(ussr,commonbloc1,indonesia).
t(cuba,relintergovorgs,poland).
t(usa,intergovorgs,brazil).
t(china,commonbloc0,netherlands).
t(china,intergovorgs3,egypt).
t(usa,intergovorgs3,uk).
t(usa,relintergovorgs,brazil).
t(usa,militaryalliance,indonesia).
t(indonesia,intergovorgs,india).
t(poland,independence,netherlands).
t(jordan,relngo,uk).
t(brazil,ngo,usa).
t(uk,timesincewar,china).
t(poland,intergovorgs3,brazil).
t(burma,embassy,uk).
t(netherlands,unweightedunvote,israel).
t(israel,ngo,brazil).
t(cuba,boycottembargo,uk).
t(usa,relngo,brazil).
t(netherlands,ngo,brazil).
t(cuba,embassy,ussr).
t(usa,treaties,india).
t(ussr,independence,uk).
t(china,intergovorgs3,netherlands).
t(china,ngoorgs3,israel).
t(netherlands,intergovorgs,israel).
t(cuba,independence,brazil).
t(israel,commonbloc1,uk).
t(china,embassy,netherlands).
t(india,relngo,usa).
t(egypt,expeldiplomats,uk).
t(netherlands,blockpositionindex,ussr).
t(uk,unweightedunvote,burma).
t(jordan,relintergovorgs,ussr).
t(poland,timesinceally,usa).
t(egypt,reldiplomacy,ussr).
t(ussr,independence,cuba).
t(ussr,nonviolentbehavior,uk).
t(china,treaties,cuba).
t(egypt,reltreaties,jordan).
t(egypt,relexports,china).
t(usa,conferences,ussr).
t(india,intergovorgs,netherlands).
t(india,ngo,netherlands).
t(netherlands,embassy,indonesia).
t(usa,pprotests,indonesia).
t(indonesia,intergovorgs3,usa).
t(uk,unweightedunvote,poland).
t(uk,timesinceally,netherlands).
t(egypt,relintergovorgs,netherlands).
t(usa,commonbloc1,israel).
t(usa,weightedunvote,egypt).
t(poland,relngo,india).
t(ussr,economicaid,india).
t(india,officialvisits,ussr).
t(ussr,negativebehavior,china).
t(jordan,relintergovorgs,brazil).
t(uk,weightedunvote,brazil).
t(israel,relstudents,usa).
t(usa,intergovorgs3,egypt).
t(burma,commonbloc2,indonesia).
t(burma,unweightedunvote,uk).
t(brazil,blockpositionindex,poland).
t(egypt,severdiplomatic,uk).
t(egypt,relngo,poland).
t(usa,economicaid,egypt).
t(usa,nonviolentbehavior,cuba).
t(poland,commonbloc1,indonesia).
t(uk,timesincewar,burma).
t(indonesia,relintergovorgs,uk).
t(india,nonviolentbehavior,indonesia).
t(ussr,reldiplomacy,cuba).
t(brazil,relintergovorgs,uk).
t(china,blockpositionindex,uk).
t(indonesia,embassy,jordan).
t(indonesia,intergovorgs,egypt).
t(israel,ngoorgs3,netherlands).
t(jordan,relngo,poland).
t(uk,treaties,israel).
t(uk,negativebehavior,indonesia).
t(egypt,reldiplomacy,indonesia).
t(india,intergovorgs,usa).
t(indonesia,ngoorgs3,israel).
t(jordan,commonbloc2,india).
t(ussr,reldiplomacy,burma).
t(uk,reltourism,egypt).
t(brazil,commonbloc0,ussr).
t(usa,tourism,jordan).
t(netherlands,weightedunvote,brazil).
t(poland,embassy,jordan).
t(jordan,ngoorgs3,india).
t(china,violentactions,usa).
t(uk,tourism3,ussr).
t(netherlands,intergovorgs3,brazil).
t(poland,treaties,uk).
t(netherlands,independence,cuba).
t(netherlands,timesinceally,india).
t(uk,timesinceally,poland).
t(indonesia,commonbloc1,poland).
t(brazil,reldiplomacy,poland).
t(poland,blockpositionindex,usa).
t(ussr,commonbloc0,brazil).
t(brazil,independence,ussr).
t(indonesia,nonviolentbehavior,usa).
t(uk,warning,indonesia).
t(brazil,weightedunvote,netherlands).
t(israel,intergovorgs3,uk).
t(ussr,reltreaties,usa).
t(brazil,independence,netherlands).
t(uk,treaties,egypt).
t(netherlands,independence,brazil).
t(cuba,relngo,israel).
t(uk,commonbloc0,china).
t(poland,independence,usa).
t(burma,intergovorgs,india).
t(indonesia,conferences,ussr).
t(uk,reltourism,brazil).
t(netherlands,commonbloc1,india).
t(burma,intergovorgs3,usa).
t(poland,reldiplomacy,netherlands).
t(burma,relexports,uk).
t(egypt,intergovorgs,brazil).
t(usa,independence,uk).
t(ussr,independence,egypt).
t(egypt,embassy,indonesia).
t(uk,relexportbooks,india).
t(china,relngo,usa).
t(israel,embassy,cuba).
t(uk,intergovorgs,egypt).
t(egypt,commonbloc2,israel).
t(brazil,commonbloc1,israel).
t(ussr,expeldiplomats,usa).
t(poland,ngoorgs3,brazil).
t(china,reldiplomacy,india).
t(uk,conferences,ussr).
t(netherlands,weightedunvote,jordan).
t(cuba,commonbloc1,jordan).
t(india,unweightedunvote,uk).
t(indonesia,intergovorgs3,uk).
t(poland,embassy,ussr).
t(netherlands,weightedunvote,uk).
t(india,booktranslations,usa).
t(china,timesincewar,usa).
t(usa,weightedunvote,burma).
t(usa,officialvisits,brazil).
t(uk,negativebehavior,india).
t(egypt,intergovorgs,india).
t(brazil,reldiplomacy,india).
t(jordan,commonbloc2,egypt).
t(egypt,booktranslations,uk).
t(brazil,ngoorgs3,poland).
t(jordan,relintergovorgs,egypt).
t(india,intergovorgs3,egypt).
t(poland,intergovorgs,netherlands).
t(ussr,commonbloc1,egypt).
t(ussr,blockpositionindex,israel).
t(netherlands,embassy,cuba).
t(poland,ngo,uk).
t(brazil,reldiplomacy,netherlands).
t(indonesia,accusation,china).
t(usa,reltourism,uk).
t(netherlands,commonbloc2,usa).
t(ussr,embassy,israel).
t(cuba,timesinceally,egypt).
t(uk,intergovorgs3,egypt).
t(cuba,timesinceally,china).
t(usa,commonbloc0,poland).
t(israel,treaties,uk).
t(india,embassy,china).
t(egypt,relngo,netherlands).
t(israel,exports3,uk).
t(cuba,ngoorgs3,netherlands).
t(china,negativebehavior,usa).
t(brazil,relexports,netherlands).
t(indonesia,intergovorgs3,netherlands).
t(burma,embassy,usa).
t(usa,ngo,netherlands).
t(cuba,timesinceally,poland).
t(burma,relintergovorgs,netherlands).
t(burma,relbooktranslations,usa).
t(egypt,reltreaties,netherlands).
t(india,timesinceally,egypt).
t(usa,treaties,brazil).
t(ussr,commonbloc0,uk).
t(poland,relngo,israel).
t(cuba,reldiplomacy,poland).
t(usa,intergovorgs3,israel).
t(ussr,relngo,usa).
t(cuba,commonbloc2,ussr).
t(egypt,timesinceally,uk).
t(ussr,embassy,egypt).
t(indonesia,relstudents,egypt).
t(cuba,eemigrants,usa).
t(usa,intergovorgs,ussr).
t(ussr,weightedunvote,netherlands).
t(poland,independence,ussr).
t(netherlands,tourism,usa).
t(usa,eemigrants,uk).
t(uk,unweightedunvote,ussr).
t(uk,tourism3,netherlands).
t(cuba,intergovorgs3,brazil).
t(poland,independence,china).
t(ussr,conferences,india).
t(israel,weightedunvote,cuba).
t(netherlands,reltreaties,uk).
t(india,embassy,usa).
t(jordan,relngo,egypt).
t(usa,embassy,israel).
t(india,pprotests,china).
t(egypt,timesincewar,uk).
t(usa,commonbloc1,burma).
t(brazil,commonbloc1,jordan).
t(india,conferences,ussr).
t(egypt,commonbloc2,burma).
t(poland,timesinceally,uk).
t(israel,commonbloc1,brazil).
t(indonesia,relngo,uk).
t(netherlands,ngoorgs3,uk).
t(brazil,relintergovorgs,india).
t(cuba,relngo,usa).
t(uk,reltreaties,netherlands).
t(israel,commonbloc2,india).
t(ussr,negativecomm,china).
t(usa,reltourism,ussr).
t(usa,relexportbooks,netherlands).
t(india,relexports,egypt).
t(egypt,independence,china).
t(jordan,reltreaties,egypt).
t(ussr,economicaid,poland).
t(india,embassy,ussr).
t(poland,commonbloc1,israel).
t(china,warning,usa).
t(egypt,reldiplomacy,brazil).
t(india,commonbloc2,burma).
t(brazil,reldiplomacy,egypt).
t(israel,relbooktranslations,uk).
t(israel,commonbloc2,jordan).
t(usa,conferences,india).
t(usa,relbooktranslations,ussr).
t(uk,weightedunvote,burma).
t(egypt,reldiplomacy,netherlands).
t(ussr,unweightedunvote,netherlands).
t(jordan,embassy,usa).
t(cuba,commonbloc0,uk).
t(ussr,relngo,uk).
t(egypt,unweightedunvote,uk).
t(cuba,ngo,usa).
t(cuba,blockpositionindex,netherlands).
t(india,duration,china).
t(china,timesincewar,india).
t(jordan,ngoorgs3,uk).
t(india,exports3,usa).
t(indonesia,officialvisits,china).
t(egypt,relstudents,usa).
t(ussr,blockpositionindex,netherlands).
t(cuba,intergovorgs,uk).
t(usa,weightedunvote,uk).
t(egypt,commonbloc1,poland).
t(usa,negativecomm,china).
t(egypt,independence,netherlands).
t(indonesia,duration,china).
t(poland,intergovorgs,uk).
t(netherlands,ngoorgs3,poland).
t(cuba,nonviolentbehavior,usa).
t(usa,conferences,burma).
t(jordan,relbooktranslations,uk).
t(israel,relbooktranslations,ussr).
t(uk,treaties,netherlands).
t(egypt,exports3,usa).
t(usa,relexports,netherlands).
t(jordan,embassy,uk).
t(uk,intergovorgs3,israel).
t(poland,relintergovorgs,netherlands).
t(india,conferences,indonesia).
t(usa,accusation,china).
t(china,relngo,uk).
t(egypt,intergovorgs3,uk).
t(israel,relintergovorgs,brazil).
t(poland,reldiplomacy,ussr).
t(indonesia,relngo,israel).
t(china,ngoorgs3,india).
t(ussr,timesincewar,poland).
t(burma,conferences,india).
t(jordan,relintergovorgs,uk).
t(cuba,reldiplomacy,uk).
t(cuba,relintergovorgs,israel).
t(israel,ngoorgs3,poland).
t(netherlands,embassy,jordan).
t(brazil,reltreaties,poland).
t(usa,blockpositionindex,burma).
t(poland,timesinceally,netherlands).
t(israel,intergovorgs,india).
t(usa,treaties,uk).
t(netherlands,timesinceally,ussr).
t(egypt,commonbloc1,usa).
t(ussr,embassy,india).
t(netherlands,intergovorgs,cuba).
t(ussr,reltreaties,uk).
t(jordan,commonbloc2,burma).
t(poland,treaties,usa).
t(ussr,relngo,brazil).
t(uk,conferences,burma).
t(china,pprotests,uk).
t(uk,embassy,usa).
t(brazil,students,usa).
t(brazil,ngoorgs3,netherlands).
t(uk,intergovorgs3,india).
t(ussr,relexports,poland).
t(cuba,commonbloc1,egypt).
t(poland,relemigrants,usa).
t(burma,exports3,ussr).
t(ussr,ngo,netherlands).
t(uk,commonbloc2,usa).
t(egypt,reltreaties,uk).
t(ussr,unweightedunvote,uk).
t(egypt,blockpositionindex,usa).
t(usa,ngoorgs3,india).
t(china,reldiplomacy,egypt).
t(uk,conferences,india).
t(usa,commonbloc0,ussr).
t(usa,timesincewar,cuba).
t(brazil,intergovorgs3,netherlands).
t(indonesia,relngo,egypt).
t(cuba,timesinceally,brazil).
t(india,treaties,usa).
t(egypt,relintergovorgs,india).
t(uk,expeldiplomats,ussr).
t(brazil,relngo,israel).
t(usa,pprotests,ussr).
t(netherlands,independence,poland).
t(egypt,commonbloc1,ussr).
t(uk,pprotests,usa).
t(jordan,blockpositionindex,ussr).
t(china,militaryactions,india).
t(indonesia,relngo,india).
t(burma,embassy,egypt).
t(burma,intergovorgs3,uk).
t(india,conferences,brazil).
t(usa,boycottembargo,egypt).
t(burma,relintergovorgs,cuba).
t(ussr,officialvisits,india).
t(usa,boycottembargo,indonesia).
t(indonesia,severdiplomatic,cuba).
t(netherlands,embassy,brazil).
t(usa,ngo,cuba).
t(brazil,treaties,usa).
t(indonesia,negativebehavior,china).
t(egypt,ngo,india).
t(indonesia,intergovorgs,uk).
t(brazil,relintergovorgs,cuba).
t(poland,ngoorgs3,israel).
t(egypt,relintergovorgs,brazil).
t(indonesia,exports3,netherlands).
t(china,timesinceally,cuba).
t(uk,militaryalliance,netherlands).
t(brazil,timesinceally,poland).
t(india,conferences,cuba).
t(jordan,reltreaties,uk).
t(cuba,ngoorgs3,usa).
t(usa,timesincewar,china).
t(china,treaties,burma).
t(netherlands,eemigrants,usa).
t(indonesia,embassy,egypt).
