t(3,cuba,timesinceally,india).
t(3,brazil,reltreaties,egypt).
t(3,egypt,exports3,uk).
t(3,netherlands,ngo,uk).
t(3,china,reltourism,ussr).
t(3,uk,intergovorgs,israel).
t(3,ussr,releconomicaid,cuba).
t(3,ussr,embassy,indonesia).
t(3,israel,violentactions,jordan).
t(3,uk,unweightedunvote,usa).
t(3,india,intergovorgs3,brazil).
t(3,cuba,commonbloc1,brazil).
t(3,poland,unweightedunvote,israel).
t(3,israel,intergovorgs,brazil).
t(3,cuba,embassy,uk).
t(3,uk,exportbooks,netherlands).
t(3,netherlands,blockpositionindex,cuba).
t(3,cuba,blockpositionindex,uk).
t(3,poland,reltreaties,uk).
t(3,israel,weightedunvote,ussr).
t(3,netherlands,embassy,poland).
t(3,china,economicaid,egypt).
t(3,ussr,treaties,china).
t(3,usa,independence,poland).
t(3,usa,commonbloc0,cuba).
t(3,israel,unweightedunvote,netherlands).
t(3,ussr,relexports,uk).
t(3,israel,militaryalliance,usa).
t(3,india,embassy,uk).
t(3,cuba,embassy,indonesia).
t(3,cuba,officialvisits,egypt).
t(3,ussr,timesinceally,uk).
t(3,ussr,officialvisits,poland).
t(3,cuba,negativecomm,usa).
t(3,ussr,reldiplomacy,israel).
t(3,egypt,ngo,brazil).
t(3,ussr,relintergovorgs,india).
t(3,china,intergovorgs3,brazil).
t(3,uk,independence,brazil).
t(3,uk,intergovorgs,ussr).
t(3,poland,timesinceally,ussr).
t(3,netherlands,embassy,usa).
t(3,china,nonviolentbehavior,ussr).
t(3,china,relintergovorgs,india).
t(3,brazil,commonbloc1,indonesia).
t(3,israel,weightedunvote,usa).
t(3,burma,ngoorgs3,uk).
t(3,ussr,commonbloc1,burma).
t(3,netherlands,intergovorgs,poland).
t(3,burma,embassy,ussr).
t(3,burma,intergovorgs3,netherlands).
t(3,indonesia,militaryactions,china).
t(3,cuba,commonbloc1,india).
t(3,uk,conferences,usa).
t(3,jordan,commonbloc1,usa).
t(3,poland,embassy,israel).
t(3,uk,violentactions,indonesia).
t(3,china,negativecomm,usa).
t(3,india,embassy,egypt).
t(3,brazil,independence,poland).
t(3,usa,tourism,uk).
t(3,china,treaties,ussr).
t(3,uk,blockpositionindex,cuba).
t(3,brazil,conferences,uk).
t(3,cuba,negativebehavior,indonesia).
t(3,netherlands,timesinceally,usa).
t(3,ussr,conferences,usa).
t(3,uk,ngoorgs3,india).
t(3,ussr,timesinceally,netherlands).
t(3,burma,commonbloc2,israel).
t(3,burma,relintergovorgs,indonesia).
t(3,ussr,embassy,poland).
t(3,poland,treaties,china).
t(3,netherlands,tourism3,egypt).
t(3,china,commonbloc1,indonesia).
t(3,china,blockpositionindex,netherlands).
t(3,ussr,independence,jordan).
t(3,netherlands,intergovorgs,usa).
t(3,cuba,dependent,usa).
t(3,china,reldiplomacy,burma).
t(3,usa,blockpositionindex,poland).
t(3,india,relintergovorgs,indonesia).
t(3,usa,timesinceally,brazil).
t(3,usa,ngoorgs3,brazil).
t(3,burma,reldiplomacy,poland).
t(3,brazil,reltreaties,usa).
t(3,china,embassy,uk).
t(3,usa,pprotests,poland).
t(3,israel,timesincewar,egypt).
t(3,cuba,weightedunvote,israel).
t(3,china,duration,india).
t(3,china,negativecomm,ussr).
t(3,uk,independence,netherlands).
t(3,indonesia,negativebehavior,ussr).
t(3,indonesia,treaties,china).
t(3,egypt,reldiplomacy,burma).
t(3,poland,reldiplomacy,brazil).
t(3,poland,relintergovorgs,brazil).
t(3,poland,ngo,ussr).
t(3,israel,ngoorgs3,usa).
t(3,jordan,reldiplomacy,india).
t(3,cuba,embassy,india).
t(3,brazil,conferences,poland).
t(3,usa,relintergovorgs,india).
t(3,poland,relbooktranslations,ussr).
t(3,poland,relbooktranslations,uk).
t(3,cuba,treaties,china).
t(3,usa,tourism,egypt).
t(3,usa,ngo,brazil).
t(3,egypt,intergovorgs3,israel).
t(3,burma,embassy,indonesia).
t(3,china,reltreaties,indonesia).
t(3,china,embassy,cuba).
t(3,israel,embassy,usa).
t(3,brazil,ngoorgs3,israel).
t(3,egypt,timesinceally,brazil).
t(3,india,commonbloc2,egypt).
t(3,jordan,warning,israel).
t(3,jordan,embassy,ussr).
t(3,poland,embassy,brazil).
t(3,uk,conferences,brazil).
t(3,ussr,intergovorgs3,brazil).
t(3,netherlands,unweightedunvote,poland).
t(3,jordan,emigrants3,usa).
t(3,poland,relngo,brazil).
t(3,israel,relexports,netherlands).
t(3,uk,accusation,ussr).
t(3,jordan,militaryalliance,egypt).
t(3,ussr,timesinceally,cuba).
t(3,ussr,ngo,uk).
t(3,india,reltreaties,netherlands).
t(3,poland,reltourism,ussr).
t(3,israel,weightedunvote,egypt).
t(3,indonesia,embassy,uk).
t(3,uk,exportbooks,china).
t(3,indonesia,relintergovorgs,cuba).
t(3,burma,embassy,china).
t(3,india,negativecomm,china).
t(3,poland,exports3,uk).
t(3,ussr,intergovorgs3,israel).
t(3,burma,relngo,egypt).
t(3,usa,treaties,poland).
t(3,burma,relbooktranslations,uk).
t(3,egypt,intergovorgs,israel).
t(3,burma,ngoorgs3,india).
t(3,cuba,independence,uk).
t(3,israel,relngo,netherlands).
t(3,ussr,ngo,usa).
t(3,israel,unweightedunvote,usa).
t(3,uk,independence,ussr).
t(3,netherlands,commonbloc0,ussr).
t(3,uk,relstudents,usa).
t(3,uk,economicaid,india).
t(3,uk,embassy,cuba).
t(3,burma,commonbloc2,egypt).
t(3,cuba,conferences,poland).
t(3,burma,reldiplomacy,china).
t(3,china,independence,egypt).
t(3,cuba,intergovorgs,brazil).
t(3,burma,weightedunvote,usa).
t(3,egypt,commonbloc1,cuba).
t(3,china,timesinceally,egypt).
t(3,jordan,unweightedunvote,uk).
t(3,indonesia,commonbloc2,egypt).
t(3,poland,ngoorgs3,netherlands).
t(3,indonesia,relbooktranslations,usa).
t(3,uk,exports3,usa).
t(3,brazil,embassy,indonesia).
t(3,uk,exports3,india).
t(3,ussr,intergovorgs3,egypt).
t(3,india,relintergovorgs,egypt).
t(3,uk,reltourism,netherlands).
t(3,indonesia,unoffialacts,india).
t(3,poland,relexports,ussr).
t(3,netherlands,intergovorgs,egypt).
t(3,netherlands,timesinceally,brazil).
t(3,poland,tourism3,ussr).
t(3,brazil,intergovorgs3,israel).
t(3,china,timesinceally,netherlands).
t(3,usa,reltourism,brazil).
t(3,egypt,relintergovorgs,indonesia).
t(3,burma,embassy,israel).
t(3,china,negativecomm,indonesia).
t(3,cuba,ngoorgs3,brazil).
t(3,ussr,relngo,netherlands).
t(3,uk,treaties,cuba).
t(3,brazil,reltreaties,india).
t(3,israel,eemigrants,usa).
t(3,ussr,ngoorgs3,usa).
t(3,uk,embassy,poland).
t(3,netherlands,ngoorgs3,usa).
t(3,brazil,ngo,israel).
t(3,cuba,reldiplomacy,india).
t(3,india,militaryactions,china).
t(3,usa,intergovorgs,egypt).
t(3,poland,ngoorgs3,uk).
t(3,china,timesinceally,india).
t(3,usa,timesinceally,poland).
t(3,egypt,negativecomm,israel).
